osx_image: xcode7.2
language: objective-c
cache: cocoapods

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build -project Compass.xcodeproj -scheme Compass-iOS -sdk iphonesimulator
- xctool test -project Compass.xcodeproj -scheme Compass-iOS -sdk iphonesimulator