osx_image: xcode7.2
language: objective-c
cache: cocoapods

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xctool clean build -workspace Compass.xcworkspace -scheme Compass-iOS -sdk iphonesimulator
- xctool test -workspace Compass.xcworkspace -scheme Compass-iOS -sdk iphonesimulator
- xctool clean build -workspace Compass.xcworkspace -scheme Compass-Mac -sdk macosx
- xctool test -workspace Compass.xcworkspace -scheme Compass-Mac -sdk macosx
